sudo: false
dist: trusty
language: python
env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost/django_tpq
  matrix:
  - DJANGO=1.10
services:
- postgresql
addons:
  postgresql: '9.5'
python:
- '3.5'
install:
- make dependencies
before_script:
- psql -c 'create database django_tpq' -U postgres
script:
- make travis
after_success:
- make coveralls
deploy:
  provider: pypi
  user: "Ben.Timby"
  password:
    secure: "E55W9Q7yVAXaX5EOT6+sEwxovSUnTNLwBFhp4PJmYDSPpihDQX77MmPPA8ecKCp0C8Mvus28/nYlogsNHUxoK8kMat70p+LkSEsYKn9WmrLRMMlpLZj++Z7YXHRyqj9rmF2bzzdZNHWKB+jrEy2+4q0YVSMqm6cx5GMwGU3jgcIszAjgG9LLAyuyTNt79EEs4VuSo8y+JHZGBeQTxaEg2a21gV1K3MIb7sfRqJrLBQCiu41ZbvpiSxZ9D4b7WIL9GzOgn4rrU7LUcPIy/wctVvIFJkrU2jZ+qpsJr/6HUudOH251qFE3VwaM9Fo9Uu0r1SfHKDkMJEIdJMMbv6f57fAlQ+aVxu2NQwovwwNVA0Ur4h1ebgRqvqSXa14hgMtEwnKv3NDyznn8tSFrSJTodcSgs3N/qoQ5yyVgJCmnMk4jCgX14OhZjTDmVbPVYr80Am2TdOhta8q0OZ6t1B5pXRqwiWMPd7nv3lDbLsj3aAKHL/LsHlkDq3IWeHZaR0m6v8ZCwxv/Inmg79qOVVmN4QmCb8EfTLBnkxFfx+CBz6Rkefx8Z6crRxirqdMPhimoz2h3rFQXJ8UJn7eou9kw4IA9Xle5B4MOEI3QyF8h/8CM6DL/GfVEYMM59hakkmm5QMLftsTiCHfEEK6sB0UH+8VHJGmRhWC0aIPkgPgCX8c="
  on:
    tags: true
