# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 02:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import tpq


def forwards(apps, schema_editor):
    with tpq.Queue('futures_futurequeue', conn=schema_editor.connection) as q:
        q.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureQueue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FutureStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('running', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(forwards, hints={'model_name': 'FutureQueue'})
    ]
